### PR TITLE
Add support for common package managers

### PR DESCRIPTION
**Pull request by philippwaller**
Add support for common package managers
---

This PR adds support for the following package managers:
- apk
- dnf
- zypper
- pacman

### CODE REVIEW

**Comment by philippwaller** [comment]
Hey @robertdebock, sorry for pushing but do you have an opinion on this PR?

**Comment by robertdebock** [comment]
Looks good. Sorry for the late reply. Let's wait for CI and pull when successful.

**Comment by robertdebock** [comment]
The build failures have been resolved in `master`. Can you rebase the PR to `master`?

**Comment by philippwaller** [comment]
Sorry @robertdebock, it took a while. It should be fine now and is ready to go.

BTW: I did the same implementation in this PR: robertdebock/ansible-role-bootstrap#57. Unfortunately, ansible does not provide a generic module to update packages. But I put it on my bucket lists for rainy days 😉.

**Comment by philippwaller** [comment]
PR is back on track and ready to merge

**Comment by philippwaller** [comment]
@robertdebock: I have implemented an update similar to the one in PR robertdebock/ansible-role-bootstrap#57. Thank you for your work on this matter.

**Pull request merged**
